schema_version = "1.0.0"

id = "midnight_blue_theme"
version = "0.0.2"
name = "Midnight Blue"
tagline = "Blender blues after midnight"
maintainer = "Mingwei Lim"
type = "theme"

website = "https://github.com/williamchange/blender-themes"
tags = ["Dark"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]