# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
#"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
sort_by        = "natural"
linemode       = "size"

[opener]
edit = [
  { run = "${EDITOR:-vi} %s", desc = "$EDITOR",      for = "unix", block = true },
  { run = 'sudoedit %s', desc = "sudoedit", block = true, for = "unix" },
]
play = [
  { run = "xdg-open %s1",    desc = "Play", for = "linux", orphan = true },
	{ run = 'mpv --force-window %s1', orphan = true, for = "unix" },
  { run = "mediainfo %s1; echo 'Press enter to exit'; read _", block = true, desc = "Show media info", for = "unix" },
]
open = [
  { run = "cp %s1 ~/.config/wallpaper/wallpaper.png; killall swaybg; niri msg action spawn -- swaybg -i ~/.config/wallpaper/wallpaper.png", desc = "Set as Wallpaper", for = "unix" },
]

[preview]
wrap = "yes"
image_filter = "lanczos3"
