AMD_VULKAN_ICD=RADV
EDITOR=nvim
ELECTRON_OZONE_PLATFORM_HINT=wayland
FZF_DEFAULT_COMMAND='fd --hidden --follow --exclude .git --one-file-system'
MESA_SHADER_CACHE_MAX_SIZE=12G
PROTON_USE_NTSYNC=1
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_QPA_PLATFORMTHEME=qt5ct:qt6ct
QT_QPA_PLATFORM=wayland;xcb
QT_WAYLAND_DISABLE_WINDOWDECORATION=1
TERMINAL=kitty
TERM=kitty
XCURSOR_SIZE=28
XCURSOR_THEME=BreezeX-RoséPine
XDG_SESSION_TYPE=wayland
